site_name: Robin F. De Guzman
theme: united
copyright: 'Robin F. De Guzman | rfdeguzman21@gmail.com | 09165933905'
site_author: 'Robin F. De Guzman'
docs_dir: src
site_dir: docs
extra_css:
    - css/main.css
dev_addr: '0.0.0.0:8000'
remote_branch: master
pages:
    - Home: index.md
    - Skills: skills.md
    - Projects: projects.md
    - Education: education.md