site_name: Robin F. De Guzman

theme: 
    name: material

copyright: 'Robin F. De Guzman | rfdeguzman21@gmail.com | 0916 593 3905'

site_author: 'Robin F. De Guzman'

docs_dir: src

site_dir: docs

extra_css:
    - css/main.css

pages:
    - Home: index.md
    - Experience: experiences.md
    - Skills: skills.md
    - Projects: projects.md
    - Education: education.md
    - Download resume: downloads/robindeguzman_resume.docx

dev_addr: '0.0.0.0:8000'

remote_branch: master

copyright: 'Copyright &copy; 2018 - 2019 Robin F. De Guzman'

google_analytics:
    - 'UA-115313253-1'
    - auto

markdown_extensions:
  - pymdownx.tilde
  - footnotes
  - markdown.extensions.admonition
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.arithmatex
  - pymdownx.critic
