site_name: Robin F. De Guzman

theme: 
  name: material
  language: en
  palette:
    primary: 'Deep purple'
    accent: 'Deep purple'

copyright: 'Robin F. De Guzman | rfdeguzman21@gmail.com | 09165933905'

site_author: 'Robin F. De Guzman'

docs_dir: src

site_dir: docs

extra_css:
    #- css/main.css

dev_addr: '0.0.0.0:8000'

remote_branch: master

copyright: 'Copyright &copy; 2018 - 2019 Robin F. De Guzman'

pages:
    - Home: index.md
    - Skills: skills.md
    - Projects: projects.md
    - Education: education.md

markdown_extensions:
  - pymdownx.tilde
  - footnotes
  - markdown.extensions.admonition
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.arithmatex
  - pymdownx.critic
