site_name: Robin F. De Guzman
theme: cinder
docs_dir: src
site_dir: docs
dev_addr: '0.0.0.0:8000'
pages:
    - Home: index.md
    - Skills: skills.md
    - Projects: projects.md
    - Education: education.md